---@class Separator
---@field start_symbol string
---@field body_symbol string
---@field end_symbol string
---@field buffer integer
---@field win integer|nil
---@field config { style: string, border: string, relative: string, zindex: integer, focusable: boolean, height: integer, width: integer, row: integer, col: integer }
---@field extmarks table
---@field _show boolean
